apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: ldap
spec:
  selector:
    app: ldap
  ports:
    - name: insecure
      protocol: TCP
      port: 389
    - name: secure
      protocol: TCP
      port: 636
  type: NodePort