version: "3.7"

services:
  mq-client:
    build:
      context: .
    environment:
      - TARGET_Q=REPLACE_TARGET_Q
      - TARGET_QMGR_GET=REPLACE_QMGR_GET
      - TARGET_QMGR_PUT=REPLACE_QMGR_PUT
      - TEST_MESSAGE=REPLACE_TEST_MESSAGE
      - MQSSLKEYR=/client-volume/REPLACE_KDB
      #- MQSERVER='DEV.APP.SVRCONN/TCP/cqm5-ibm-mq-qm-mq-2.banking-2021-01-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud(443)'